// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sysdmrfkkvbmwifzspkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5c2RtcmZra3ZibXdpZnpzcGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDM3MTcsImV4cCI6MjA2MzMxOTcxN30.UqY9RdAqyLm1ByA6auFxFhPwQnzRvbOQUI4-yvTWS9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);